
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity" ]
      interval: 5s
      timeout: 3s
      retries: 20
    ports: ["5672:5672","15672:15672"]

  model_api:
    build: ../services/model_api
    environment:
      - MODEL_PATH=/app/artifacts/model.pkl
      - MODEL_CONFIG=/app/artifacts/model_config.json
    volumes:
      - ../artifacts:/app/artifacts:ro
      - ../services/model_api:/app
    ports: ["8001:8001"]
    depends_on: [rabbitmq]

  rules_api:
    build: ../services/rules_api
    environment:
      - RULES_PATH=/app/config/rules.yaml
    volumes:
      - ../config:/app/config:ro
      - ../services/rules_api:/app
    ports: ["8002:8002"]
    depends_on: [rabbitmq]

  publisher:
    build: ../services/publisher
    depends_on: [rabbitmq]
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - FILE_PATH=/data/transactions_sample.jsonl
      - QUEUE=transactions.raw
      - RATE=0                 # 0 = fastest; set e.g. 100 for 100 msg/sec
    volumes:
      - ../data:/data:ro       # to read your JSONL from host
    restart: "no"              # run once and exit

  stream_worker:
    build: ../services/stream_worker
    environment:
      - MQ_HOST=rabbitmq
      - MODEL_API=http://model_api:8001
      - RULES_API=http://rules_api:8002
      - ALERT_THRESHOLD=0.75
      - MQ_USER=guest
      - MQ_PASS=guest
    volumes:
      - ../services/stream_worker:/app
      - ../config:/app/config:ro
    depends_on: #[rabbitmq, model_api, rules_api]
      rabbitmq:
        condition: service_healthy
      model_api:
        condition: service_started
      rules_api:
        condition: service_started

  agent:
    build: ../services/agent
    environment:
      - MQ_HOST=rabbitmq
      - MQ_USER=guest
      - MQ_PASS=guest
      - DB_PATH=/data/fraud.db
      - POLICY_PATH=/app/config/decision_policy.json
      - OLLAMA_URL=http://host.lima.internal:11434/api/chat
      - AGENT_MODEL=qwen3:8b
      - FALLBACK_ENABLE=true
    volumes:
      - ../services/agent:/app
      - ../config:/app/config:ro
      - ../data:/data
    depends_on: #[rabbitmq]
      rabbitmq:
        condition: service_healthy

  ui:
    build: ../services/ui
    environment:
      - DB_PATH=/data/fraud.db
      - PAGE_SIZE=200
    volumes:
      - ../services/ui:/app
      - ../data:/data:ro
    ports: ["8501:8501"]
    depends_on: [rabbitmq, agent]
